reddit_ai_news:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'REDDIT_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'REDDIT_AI_NEWS') }}"
      schema: STAGING
      threads: 1
